core/jreleaser-utils/src/main/java/org/jreleaser/util/signing/Keyring.java
=> [#152] check if a given key can be used for signing

CONTRIBUTING.adoc
=> Fix email address

apps/jreleaser/src/main/java/org/jreleaser/cli/Release.java, core/jreleaser-engine/src/main/java/org/jreleaser/engine/context/ModelAutoConfigurer.java, core/jreleaser-model/src/main/java/org/jreleaser/model/GitService.java, plugins/jreleaser-ant-tasks/src/main/java/org/jreleaser/ant/tasks/JReleaserAutoConfigReleaseTask.java, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/dsl/GitService.groovy, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/AbstractGitService.groovy, plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/GitService.java, plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/JReleaserAutoConfigReleaseMojo.java, plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/internal/JReleaserModelConverter.java, sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java
=> [changelog] add possibility to overwrite previous tag Resolves #382

.github/PULL_REQUEST_TEMPLATE.md
=> [chore] fix contribution guideline link Fixes #384 [ci skip]

sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java
Relates to #386
Experiencing a NPE when the title was set but no body defined.
=> [changelog] fix npe in regex prefix logic. Relates to #386

apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_nl.properties
=> #503 additional translations

apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_es.properties, apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_it.properties
=> [translation] Update CLI Italian translation

apps/jreleaser/src/main/resources/org/jreleaser/cli/Banner_zh_TW.properties, apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_zh_TW.properties
first attempt at adding Chinese translation
=> [translation] Add CLI Chinese translation

apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_pt_BR.properties
Fixes #508 
Updates current translation for messages in CLI
=> Updates Brazilian Portuguese translations

apps/jreleaser/src/main/resources/org/jreleaser/cli/Banner_ru.properties
=> Fix a typo in the Russian translation

apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_de.properties
=> Update German CLI bundle

apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_ca.properties, core/jreleaser-utils/src/main/resources/org/jreleaser/bundle/Messages_ca.properties
=> Catalan translation update

apps/jreleaser/src/main/resources/org/jreleaser/cli/Banner_ko.properties, apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_ko.properties
Please check the translation files you want to add/fix/update:
A list of language codes can be found at https://sda.berkeley.edu/man41h/localelist.htm
=> [translation] Add Korean translation

core/jreleaser-model/src/main/java/org/jreleaser/model/Twitter.java, core/jreleaser-model/src/main/java/org/jreleaser/model/validation/TwitterValidator.java, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/dsl/Twitter.groovy, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/TwitterImpl.groovy, sdks/twitter-java-sdk/src/main/java/org/jreleaser/sdk/twitter/Twitter.java, sdks/twitter-java-sdk/src/main/java/org/jreleaser/sdk/twitter/TwitterAnnouncer.java, sdks/twitter-java-sdk/src/main/java/org/jreleaser/sdk/twitter/UpdateStatusTwitterCommand.java, sdks/twitter-java-sdk/src/test/java/org/jreleaser/sdk/twitter/UpdateStatusTwitterCommandTest.java
=> feat(announce): Add thread support to Twitter. Resolves #853

apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages.properties, apps/jreleaser/src/main/resources/org/jreleaser/cli/Messages_it.properties
This updates the Italian translation of CLI resources.
=> i18n: Update Italian translation of CLI resources

plugins/jreleaser-ant-tasks/src/main/java/org/jreleaser/ant/tasks/JReleaserAutoConfigReleaseTask.java
Adds  additional properties in ANT release auto config.
=> feat(ant): Support additional properties in release auto-config. Relates to #937

plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/JReleaserAutoConfigReleaseMojo.java
Relates to jreleaser#937
Support additional properties in release auto-config.
=> feat(maven): Support additional properties in release auto-config. Relates to jreleaser#937

core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/release/Changelog.java, sdks/jreleaser-git-java-sdk/src/test/java/org/jreleaser/sdk/git/ChangelogGeneratorUnitTest.java
Fixes #957?
https://github.com/jreleaser/jreleaser/issues/957
=> fix: Ease the regex search for contributors

.vscode/settings.json, api/jreleaser-model-api/src/main/java/org/jreleaser/model/api/announce/Announce.java, api/jreleaser-model-api/src/main/java/org/jreleaser/model/api/announce/DiscourseAnnouncer.java, core/jreleaser-engine/jreleaser-engine.gradle, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/JReleaserSupport.java, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/announce/Announce.java, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/announce/DiscourseAnnouncer.java, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/announce/AnnouncersValidator.java, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/announce/DiscourseAnnouncerValidator.java, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/announcers/discourse.tpl, sdks/jreleaser-discourse-java-sdk/gradle.properties, sdks/jreleaser-discourse-java-sdk/jreleaser-discourse-java-sdk.gradle, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseAnnouncer.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseAnnouncerBuilder.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseAnnouncerBuilderFactory.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseException.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/DiscourseSdk.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/ActionsSummary.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/Category.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/CategoryList.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/CategoryResponse.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/DiscourseAPI.java, sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/Post.java, sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/ApiEndpoints.java, sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/DiscoursePostTest.java, sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/Stubs.java, sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/WireMockExtension.java
Fixes #991
I added the Discourse SDK and added it to Announce.
Discourse is an OpenSource-based forum and is used in many development community
I followed the keywords in the [API](http://docs.discourse.org) document as much as possible.
Thank you.
=> feat(announce): Add discourse sdk

README.adoc
Incorrect link to Dagger has been corrected.
=> docs: Fix link in README.md [skip ci]

core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/packagers/ChocolateyPackagerValidator.java
Fixes #1313
Adds validation for the tag list not being empty
=> fix: Add validation for tags to ChocolateyPackagerValidator

README.adoc
See https://github.com/jreleaser/jreleaser/discussions/1352
=> Readme: Add "Build from source" section

sdks/jreleaser-java-sdk-commons/src/main/java/org/jreleaser/sdk/commons/RestAPIException.java
Fixes https://github.com/jreleaser/jreleaser/issues/1357
=> fix: Show the reason when RestAPIException fails a build

core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/binary/chocolatey/.github/workflows/push.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-binary/chocolatey/.github/workflows/push.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/chocolatey/.github/workflows/push.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/native-image/chocolatey/.github/workflows/push.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/native-package/chocolatey/.github/workflows/push.yml.tpl
=> fix(packagers): Changed distributionName to chocolateyPackageName.

core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/brew/formula-multi.rb.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/brew/formula.rb.tpl
Fixes https://github.com/Homebrew/homebrew-core/issues/106008
Based on this fix https://github.com/Homebrew/homebrew-core/pull/123682
=> fix(brew): resign modified dylibs

CONTRIBUTING.adoc
Just a little typo and getting the CLA sorted out. Some code contributions to follow.
Regards,
Matthias
=> docs: fix typo [ci skip]

.github/workflows/smoke-tests.yml
Stop Gradle Daemon as first command in "Cleanup" steps.
=> Stop Gradle Daemon first

sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/BlueskyAnnouncer.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/BlueskyRecordFactory.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/BlueskySdk.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/BlueskyAPI.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/CreateTextRecordRequest.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/Facet.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/Index.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/ResolveHandleResponse.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/features/Feature.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/features/LinkFeature.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/features/MentionFeature.java, sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/features/TagFeature.java, sdks/jreleaser-bluesky-java-sdk/src/test/java/org/jreleaser/sdk/bluesky/BlueskySdkTest.java, sdks/jreleaser-bluesky-java-sdk/src/test/resources/mappings/resolveHandle.json
Fixes #1611
Fixes broken hyperlinks, mentions and hashtags.
I have tagged the Jreleaser Bluesky account in some test posts, so you can verify it works.
=> fix(announce): Fixes links, mentions and hashtags for Bluesky.#1611

.github/workflows/build.yml
From https://github.com/jreleaser/jreleaser/pull/1727#issuecomment-2365321296
=> build: remove matrix expression from group name

sdks/jreleaser-mavencentral-java-sdk/src/main/java/org/jreleaser/sdk/mavencentral/MavenCentral.java
=> fix(deploy): ignore 401 errors from MavenCentral in waitForStatus()

sdks/jreleaser-s3-java-sdk/src/main/java/org/jreleaser/sdk/s3/S3ArtifactUploader.java
Fixes #1762 
An attempt to solve the problem with uploading artifact to custom S3 that doesn't response with `owner` in `GetBucketAclResponse`
=> fix(upload): S3ArtifactUploader NPE

README.adoc
Fixes #?
makes more sense when following the badge to understand what is behind the content
=> add link to Reproducible Central badge

jreleaser.yml
Fixes #1838
https://github.com/jreleaser/jreleaser/discussions/1812#discussioncomment-12655129
=> feat(build): add git to docker images

plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/dsl/deploy/maven/MavenDeployer.groovy, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/deploy/maven/AbstractMavenDeployer.groovy
https://github.com/jreleaser/jreleaser/issues/1665
Fixes yes
solves issue 1665
=> issue https://github.com/jreleaser/jreleaser/issues/1665

sdks/jreleaser-gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/GitlabReleaser.java, sdks/jreleaser-gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/api/GlRelease.java
Fixes #1932
See #1932 description
- I don't know if it's fine if this new behavior is applied by default (like implemented). I think I'm not maintainer, it's not my decision :shrug: 
- I don't know neither if we have to update the documentation to reflect this new behavior. If yes, let me known, I'll create a PR in the documentation repository.
=> feat: associate milestone in gitlab release

api/jreleaser-model-api/src/main/java/org/jreleaser/model/api/extensions/Extension.java, api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties, api/jreleaser-utils/jreleaser-utils.gradle, api/jreleaser-utils/src/main/java/org/jreleaser/util/DefaultVersions.java, core/jreleaser-engine/src/main/java/org/jreleaser/engine/context/ModelValidator.java, core/jreleaser-engine/src/main/java/org/jreleaser/extensions/internal/DefaultExtensionManager.java, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/extensions/Extension.java, gradle.properties, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/dsl/extensions/Extension.groovy, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/extensions/ExtensionImpl.groovy, sdks/jreleaser-tool-java-sdk/src/main/java/org/jreleaser/sdk/tool/AbstractTool.java, sdks/jreleaser-tool-java-sdk/src/main/java/org/jreleaser/sdk/tool/JBang.java, sdks/jreleaser-tool-java-sdk/src/main/resources/META-INF/jreleaser/tools/jbang.properties
Fixes #1952 
Adds support for using jbang to define extensions.
```
extensions:
github-summary:
jbang: misc/jreleaser-extension/githubjobsummary.java
```
=> feat: support for jbang built extensions
