jreleaser/jreleaser

core/jreleaser-model/src/main/java/org/jreleaser/model/Gitlab.java, core/jreleaser-utils/src/main/java/org/jreleaser/util/Constants.java, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/dsl/Gitlab.groovy, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/GitlabImpl.groovy, plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/Gitlab.java, plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/internal/JReleaserModelConverter.java, sdks/gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/Gitlab.java, sdks/gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/GitlabReleaser.java, sdks/gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/api/GitlabAPI.java
This PR adds the possibility to define the GitLab-specific project IDs. This closes #166.
The mentioned idea that GitLab returns multiple results and JReleaser picks the wrong one is not valid. I discovered that the query returns one result item and prefers a project in the personal space that has the same name, aka a fork. Only if the name is not an exact match, the query returns multiple results. Anyhow, the proposed solution should provide a remedy to that issue. 
I implemented as proposed in the issue. But I think this PR could do better. The SDK GitLab class uses the Model class and spreads the parameter to the submethods. With `identifier this grows even further. If the methods would directly accept git model class, `getProject` could compare the desired path of owner and name if an …
=> [gitlab] add identifier field

plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/Jreleaser.java, plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/internal/JReleaserModelConverter.java
Fixes #228
When configuring the Maven plugin, Distribution name is not taken from the XML element name.
=> [maven] Using element name to set Distribution name. Fixes #228

.gitignore
When the project is imported as a Gradle project in Eclipse, several files are created in the output directory '/bin' and '.settings' of each subproject.
Adding 'bin' and '.settings' to .gitignore avoids that the project
contains unstaged files after import.
=> Ignore files generated by Eclipse Import

README.adoc
Removed "Required Java 8" from the Jbang instructions as this not really necessary given the fact Jbang can install Java when needed.
=> [docs] Update Jbang instructions

core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/binary/snap/snap/snapcraft.yaml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-binary/snap/snap/snapcraft.yaml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/snap/snap/snapcraft.yaml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/native-image/snap/snap/snapcraft.yaml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/native-package/snap/snap/snapcraft.yaml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/single-jar/snap/snap/snapcraft.yaml.tpl
Fixes #766 
A recent Snapcraft build of mcs v0.2 failed with 
> Issues while validating snapcraft.yaml: The 'version' property does not match the required schema: snap versions need to be strings. They must also be wrapped in quotes when the value will be interpreted by the YAML parser as a non-string. Examples: '1', '1.2', '1.2.3', git (will be replaced by a git describe based version string).
=> [snap] versions need to be strings

core/jreleaser-utils/src/main/java/org/jreleaser/util/command/CommandExecutor.java, sdks/tool-sdk/src/main/java/org/jreleaser/sdk/tool/AbstractTool.java, sdks/tool-sdk/src/main/java/org/jreleaser/sdk/tool/Cosign.java, sdks/tool-sdk/src/main/java/org/jreleaser/sdk/tool/DownloadableTool.java, sdks/tool-sdk/src/main/java/org/jreleaser/sdk/tool/Upx.java
Fixes #835
DownloadableTool should be able to also verify the err-output.
In the concrete case cosign is reporting its version via the error-channel, resulting in verify to always fail.
=> Fix cosign-support by verifying against err-output

core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/binary/chocolatey/.github/workflows/push.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-binary/chocolatey/.github/workflows/push.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/chocolatey/.github/workflows/push.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/native-image/chocolatey/.github/workflows/push.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/native-package/chocolatey/.github/workflows/push.yml.tpl
The GitHub documentation is very unclear on this point but without the
pattern, the workflow is not triggered at all when creating tags.
Tested on the Quarkus project: https://github.com/quarkusio/chocolatey-bucket/commit/ea8df1e7400499b9f2881f9091ecd7b5b230c92a
=> fix(chocolatey): Add a catchall pattern for tags trigger in  workflow

core/jreleaser-model/src/main/java/org/jreleaser/model/Changelog.java, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/dsl/Changelog.groovy, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/ChangelogImpl.groovy, sdks/git-sdk/git-sdk.gradle, sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java, sdks/git-sdk/src/test/java/org/jreleaser/sdk/git/ChangelogGeneratorUnitTest.java
Fixes #858
The idea is to add a property "skipMergeCommits" and if set to true, merge commits will be skipped.
According to [git reference](https://git-scm.com/docs/git-commit-tree) we can rely on the number of parents to identify merge commits.
=> feat(changelog): Introduce property to skip merge commits in the changelog. Resolves #858

.gitignore, core/jreleaser-utils/src/main/resources/org/jreleaser/bundle/Messages.properties, sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java, sdks/git-sdk/src/main/java/org/jreleaser/sdk/git/GitSdk.java
Fixes #910 
Fixes the problem of not warning users of a possible failure when generating a changelog of a shallow copy.
=> feat(changelog): Add warning when creating a changelog of shallow copy

core/jreleaser-model/src/main/java/org/jreleaser/model/GitService.java, core/jreleaser-model/src/main/java/org/jreleaser/model/JReleaserModel.java, core/jreleaser-model/src/main/java/org/jreleaser/model/Project.java, core/jreleaser-model/src/test/java/org/jreleaser/model/JReleaserModelTest.java, core/jreleaser-utils/src/main/java/org/jreleaser/util/StringUtils.java
- Fixes #923
It fixes the `projectNameCapitalized` behavior
=> fix: `projectNameCapitalized` now handles hyphens as spaces

.github/workflows/smoke-tests-ant.yml, .github/workflows/smoke-tests-cli.yml, .github/workflows/smoke-tests-gradle.yml, .github/workflows/smoke-tests-maven.yml
This prevents executions of smoke tests on forks.
Failed jobs before this change: https://github.com/scordio/jreleaser/runs/8119647105?check_suite_focus=true
=> build: Prevent smoke test executions on forks

.github/workflows/early-access.yml, .github/workflows/release.yml, .github/workflows/smoke-tests-ant.yml, .github/workflows/smoke-tests-cli.yml, .github/workflows/smoke-tests-gradle.yml, .github/workflows/smoke-tests-maven.yml, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/binary/appimage/.github/workflows/release.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-binary/appimage/.github/workflows/release.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/appimage/.github/workflows/release.yml.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/native-image/appimage/.github/workflows/release.yml.tpl, src/jreleaser/distributions/jreleaser-standalone/appimage/.github/workflows/release.yml.tpl
Fixes https://github.com/jreleaser/jreleaser/issues/983
GitHub Actions will issue a warning when ::set-output is used.
`The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`
https://hynek.me/til/set-output-deprecation-github-actions/
=> build: Update use of set-output in workflows

plugins/jreleaser/src/main/resources/org/jreleaser/cli/Messages_it.properties
This fixes some wrong characters in the Italian translation.
=> i18n: Fix Italian translation of CLI resources.

sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java, sdks/jreleaser-git-java-sdk/src/test/java/org/jreleaser/sdk/git/ChangelogGeneratorUnitTest.java
GitHub's Dependabot has commits that contain both CR/LF and LF, the previous logic did not always split the commit message correctly
Fixes: #1042
=> fix: Detect title of commits with both line ending

core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/release/BaseReleaserValidator.java, core/jreleaser-model-impl/src/main/resources/META-INF/jreleaser/changelog/preset-conventional-commits.yml, sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java, sdks/jreleaser-git-java-sdk/src/test/java/org/jreleaser/sdk/git/ConventionalCommitUnitTest.java
Fixes #809
Introduces a new ConventionalCommit subtype of Commit, which parses the commit body according to conventional commit specification. The conventional-commit preset uses a custom changelog.format instead of replacers to achieve formatting. The changelog presets can now have a custom format.
=> feat(changelog): handle BREAKING CHANGE from footer

api/jreleaser-utils/src/main/java/org/jreleaser/util/StringUtils.java, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/JReleaserModel.java, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/release/BaseReleaser.java, core/jreleaser-model-impl/src/main/resources/META-INF/jreleaser/changelog/preset-conventional-commits.yml, sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java, sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogProvider.java, sdks/jreleaser-git-java-sdk/src/test/java/org/jreleaser/sdk/git/ChangelogGeneratorUnitTest.java, sdks/jreleaser-git-java-sdk/src/test/java/org/jreleaser/sdk/git/CommitUnitTest.java, sdks/jreleaser-git-java-sdk/src/test/java/org/jreleaser/sdk/git/ConventionalCommitUnitTest.java
Fixes #806
I reused the `ChangelogProvider.extractIssues` method so that what's displayed in the changelog is the same as the issues that are commented upon to advise they have been released.
I have placed the logic inside the `Commit` class, since it can apply to any type of commit, not just conventional ones.
I could not find a Mustache way to display something once if a list is not empty, so i added a `commitIssuesCount` property. If you know how to do so, we could get rid of that extra property, however everything i tried didn't work.
Couple of things you may want to double-check:
- i have modified the default format of the conventional-commits preset
- i have **not** modified the default format
- since there is an info log in `extractIssues`, it is logged once for each commit, and …
=> reference closed issues in changelog

api/jreleaser-logger-api/src/main/java/org/jreleaser/logging/AbstractJReleaserLogger.java, api/jreleaser-model-api/src/main/java/org/jreleaser/version/SemanticVersion.java, api/jreleaser-utils/src/main/java/org/jreleaser/util/CollectionUtils.java, api/jreleaser-utils/src/test/java/org/jreleaser/util/CollectionUtilsTest.java, core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/JpackageAssemblerProcessor.java, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/KordampJReleaserAdapter.groovy, sdks/jreleaser-codeberg-java-sdk/src/main/java/org/jreleaser/sdk/codeberg/CodebergReleaser.java, sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java, sdks/jreleaser-gitea-java-sdk/src/main/java/org/jreleaser/sdk/gitea/GiteaReleaser.java, sdks/jreleaser-gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/GitlabReleaser.java, sdks/jreleaser-webhooks-java-sdk/src/main/java/org/jreleaser/sdk/webhooks/WebhooksAnnouncer.java
Hi! Saw you recently added Sonar and wanted to reduce the number of findings; figured I'd see if I could help with a few automated fixes; hope it's appreciated.
I chose to run only a select few recipes, as these had a manageable changeset and hopefully desirable outcomes. Here's a log of what changes were made where.
```
Changes have been made to plugins/jdks-maven-plugin/build/mavenPlugin/helpMojo/org/jreleaser/jdks/maven/plugin/help/HelpMojo.java by:
org.openrewrite.java.cleanup.UseDiamondOperator
Changes have been made to sdks/jreleaser-codeberg-java-sdk/src/main/java/org/jreleaser/sdk/codeberg/CodebergReleaser.java by:
org.openrewrite.java.cleanup.EqualsAvoidsNull
Changes have been made to core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/JpackageAssemblerProcessor.java by: …
```
=> fix: Small static analysis findings

api/jreleaser-utils/src/main/java/org/jreleaser/util/StringUtils.java, api/jreleaser-utils/src/test/java/org/jreleaser/util/StringUtilsTest.java, core/jreleaser-engine/src/main/java/org/jreleaser/packagers/BrewPackagerProcessor.java
Fixes jreleaser/jreleaser#1224
See jreleaser/jreleaser#1224 . Automatic JRE/JDK ("openjdk" or "java") dependency without a version is only added if there isn't one already.
=> fix: default to unversioned jdk dependency in brew (#1224)

core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-archive/java-archive/bin/launcher.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/single-jar/appimage/launcher.tpl
Resolves #1284. As far as I can see, the same pattern isn't used anywhere else except in the jlink templates where it should be correct. The Windows .bat launchers look OK too (not tested, but there's a goto that skips to the right place).
Fixes #1284.
If no JAVA_HOME is found but a java executable is on the PATH (checked using which), the script should go ahead using that instead of relying on JAVA_HOME.
=> fix(assemble): launchers should work without JAVA_HOME if java is found

api/jreleaser-model-api/src/main/java/org/jreleaser/version/ChronVer.java, api/jreleaser-model-api/src/test/java/org/jreleaser/version/ChronVerTest.java
Fixes #1295 
Allows chronver release versions like '2023.03.26-latest' 
=> fix(chronver): Fix chronver version_parsing regex 

sdks/jreleaser-java-sdk-commons/src/main/java/org/jreleaser/sdk/commons/AbstractMavenDeployer.java, sdks/jreleaser-tool-java-sdk/src/main/java/org/jreleaser/sdk/tool/PomChecker.java
Fixes #1397
Add the ``--no-fail-on-warning`` flag when running pomchecker when the version is above or equal 1.9.0.
cc: @elektro-wolle @fgaignat @jankohout95
=> fix(deployer): add support for no fail on warning flag

core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/packagers/DockerPackagerValidator.java, plugins/jreleaser-gradle-plugin/src/main/groovy/org/jreleaser/gradle/plugin/internal/dsl/packagers/DockerPackagerImpl.groovy
resolves two issues. name value set to username. name value set prematurely before parent tap values are merged.
https://github.com/jreleaser/jreleaser/issues/1438
See issue above
=> fix: honor gradle task property packagers.docker.repository.name

CONTRIBUTING.adoc, sdks/jreleaser-git-java-sdk/src/main/java/org/jreleaser/sdk/git/ChangelogGenerator.java
Fixes Issue #1481
Hi, I am pretty new to GitHub and coding in general. I stumbled across this project and thought it was super cool and wanted to contribute in any way possible. I saw the attached issue and wanted to give it a stab as it was marked good-first-issue. Let me know if this properly fixes the issue and if there is anything I can do on my end to move the PR along. Thanks, any help and guidance is appreciated!
In addition to fixing the issue, I also fixed an adoc internal cross-reference documentation bug present in the `CONTRIBUTING.adoc`
=> fix(issue/documentation): prevent outofbounds

core/jreleaser-engine/src/main/java/org/jreleaser/assemblers/JlinkAssemblerProcessor.java
Fix missing template variable binding in jlink assembler.
Add distributionJavaMainModule, distributionJavaMainClass and distributionJavaMainJar to template context in JlinkAssemblerProcessor similarly it's done in JavaArchiveAssemblerProcessor.
This fix don't try to add distributionJavaOptions as that's not used in a jlink template and assembler structure seems to be slightly different compared to java-archive.
Fixes #1496
I didn't find any tests to tweak.
=> fix(assemble): Add missing template option bindings to jlink

infra/jreleaser-test-support/src/main/java/org/jreleaser/test/WireMockStubs.java
Fixes [#1527](https://github.com/jreleaser/jreleaser/issues/1527)
**Module**: jreleaser-linkedin-java-sdk
**Tests:** 
org.jreleaser.sdk.linkedin.LinkedinSdkTest.testMessageWithExplicitOwner
org.jreleaser.sdk.linkedin.LinkedinSdkTest.testMessageWithImplicitOwner
The tests compares an API response output with hardcoded JSON string and verifies if they are equal. However, the comparision of JSON could be non-deterministic since JSON objects do not necessarily maintain the order of key:value pairs. Since the current test expects order to be maintained, the test can fail. we can use [Nondex](https://github.com/TestingResearchIllinois/nondex) Tool to detect the flakiness in test.
utilized equalToJson  which compares the two JSON strings ignoring the order of the contents.
[Apache License …
=> fix(build): Fixed Flakiness in JSON assertion

sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/api/CreateTextRecordRequest.java
Fixes #1564 
LocalDateTime is creating a date in a bad format, now it will use Instant to create a UTC format according ISO 8601 and proto datetime format
=> fix: Use Instant instead LocalDateTime in createdAt to accomplish ISO8601

core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-archive/java-archive/bin/launcher.bat.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/jlink/bin/launcher.bat.tpl
- This commit fixes various errors in windows launcher templates for java-archive and jlink.
- JAVA_OPTS as whole cannot be surrounded with quotes as windows shell would then treat that as single argument and jvm blows up. Quotes could be used with individual JAVA_OPTS arguments but that is then solely left to user.
- If java options are coming from distribution settings(ie jreleaser.yml) then we simply append to JAVA_OPTS as is without quoting.
- In java-archive template java.exe is changed to backslash like it already was in jlink template.
- Running java command also contained mixed double quoting and is fixed by removing quotes from JAVACMD.
- Classpath contained mixed triple quoting and is fixed by removing quotes from JARSDIRS and CLASSPATH
Fixes #1634
Here's few examples what a new …
=> fix(packagers): Fix quoting and path issues in windows launchers

core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/java-archive/java-archive/bin/launcher.bat.tpl, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/jlink/jlink/bin/launcher.bat.tpl
Fixes #1688.
In commit 8a9c36d, come comments starting with `#` were added in all launchers, but this syntax is not valid for .bat files.
=> fix(assemble): Use the correct comment syntax in Windows launchers

.github/workflows/build.yml
GitHub will automatically cancel concurrent jobs per PRs
=> build: Cancel concurrent PR jobs

api/jreleaser-model-api/src/main/java/org/jreleaser/version/CalVer.java, api/jreleaser-model-api/src/test/java/org/jreleaser/version/CalVerTest.java
Fixes #1728
- Updates pattern to `"(0[0-9]|[1-9][0-9]|[1-9][0-9]{2})"` for `0Y`, so `00.01.0` is correctly parsed as CALVER version
- Updates pattern to `"([0-9]|[1-9][0-9]|[1-9][0-9]{2})"` for `YY`, so `0.01.0` is correctly parsed as CALVER version
- Updates default CALVER value to `00` for `0Y`
- Fixes exceptions:
- `IllegalArgumentException: Cannot parse version '0.01.0' with '0Y.0M.MICRO'`
- `IllegalArgumentException: Cannot parse version '0.01.0' with 'YY.0M.MICRO'`
- Changes in Tests:
- Creates Parameterized Test for `CalVer#defaultOf`
- Updates existing tests to check `0Y.0M.MICRO`/`0Y.MM.MICRO`/`YY.0M.MICRO`/`YY.MM.MICRO` formats
- Changes in Docs: jreleaser/jreleaser.github.io#79
[Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was …
=> fix(core): Fix "Cannot parse CALVER version" with 0Y.0M.MICRO/YY.0M.MICRO

buildSrc/build.gradle
This change removes the dependency on log4j 2.13.2, which contains a critical vulnerability, by switching to the new maintainers package and upgrading the version.
https://github.com/GradleUp/shadow?tab=readme-ov-file#gradle-shadow
Fixes #?
=> chore: switch to new maintainers package and upgrade version

sdks/jreleaser-github-java-sdk/src/main/java/org/jreleaser/sdk/github/Github.java, sdks/jreleaser-github-java-sdk/src/test/java/org/jreleaser/sdk/github/ApiEndpoints.java, sdks/jreleaser-github-java-sdk/src/test/java/org/jreleaser/sdk/github/GithubTest.java
Fixes #1739 by handling HTTP 404 error response when deleting a GitHub tag.
=> fix(release): Do not fail when GH tag not found

sdks/jreleaser-java-sdk-commons/src/main/java/org/jreleaser/sdk/commons/RestAPIException.java
Fixes #1795 
The root cause of REST API call is becoming visible.
=> fix: RestAPIException does not ignore message body, fixes #1795

sdks/jreleaser-linkedin-java-sdk/src/main/java/org/jreleaser/sdk/linkedin/api/Message.java, sdks/jreleaser-linkedin-java-sdk/src/test/java/org/jreleaser/sdk/linkedin/LinkedinSdkTest.java
Fixes #1794
Fixes #1789
JSON payload added to the LinkedIn message.
=> fix: LinkedIn announcement Message contains distribution payload for PUBLIC MemberNetworkVisibility

plugins/jreleaser-maven-plugin/src/main/java/org/jreleaser/maven/plugin/JReleaserInitMojo.java
There is mismatch in the parameter name for overwriting between documentation and source. Reference: https://github.com/jreleaser/jreleaser.github.io/pull/83.
=> fix!: correct parameter name for overwriting jreleaser.json

core/jreleaser-engine/jreleaser-engine.gradle, core/jreleaser-engine/src/test/java/org/jreleaser/engine/init/InitTest.java, core/jreleaser-templates/src/main/resources/META-INF/jreleaser/templates/init/jreleaser.json.tpl
Fixes #1814 
Fixes the JSON syntax in template.
=> fix: correct JSON syntax in init template

api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties, core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/signing/SigningValidator.java
Fixes #1883 
GPG private keys are not always protected by a passphrase. Jreleaser should support unprotected keys.
I tried it both with a passphrase-protected key and an unprotected key, and it works for me.
=> fix(gradle): add support for blank gpg passphrase

api/jreleaser-resource-bundle/src/main/resources/org/jreleaser/bundle/Messages.properties, sdks/jreleaser-mavencentral-java-sdk/jreleaser-mavencentral-java-sdk.gradle, sdks/jreleaser-mavencentral-java-sdk/src/main/java/org/jreleaser/sdk/mavencentral/MavenCentral.java, sdks/jreleaser-mavencentral-java-sdk/src/main/java/org/jreleaser/sdk/mavencentral/MavenCentralMavenDeployer.java, sdks/jreleaser-mavencentral-java-sdk/src/test/java/org/jreleaser/sdk/mavencentral/MavenCentralErrorDecoderTest.java
Improve error messages for 401/403 in MavenCentral deploy (Fixes #1922)
Fixes #1922
This PR improves developer experience by replacing the vague "Unexpected error" during MavenCentral deployments with clear, actionable error messages.
- For 401 Unauthorized responses:
❌ Unauthorized (401): Please check your Maven Central credentials or token.
- For 403 Forbidden responses:
❌ Forbidden (403): You don't have permission to upload to this repository.
This makes it much easier to diagnose publishing issues and removes the need to dig into logs.
=> fix(mavencentral): show clear error messages for 401/403 (fixes #1922)
